version: "3.8"

volumes:
  pipelines_storage:
  neo4j_data:
  neo4j_plugins:

networks:
  demo:

services:
  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j-graph-db
    networks: ['demo']
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/my_password123
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    networks: ['demo']
    restart: always
    ports:
      - 9099:9099
    environment:
      PIPELINES_URLS: "https://github.com/BrainDriveAI/openwebui-pipelines/blob/main/pipelines/memory-filter-openai-neo4j-pipeline.py"
    volumes:
      - pipelines_storage:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
